# Use an official Python runtime as a parent image
FROM python:3.13.1-alpine3.21

# Set the working directory
WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application code
COPY . .

# Expose the port the app runs on
EXPOSE 8000

# Define the command to run the application
ENTRYPOINT ["python"]
CMD ["app.py"]