# Use an official Python runtime as a parent image
FROM python:3.12-slim as base

# Set the working directory
WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application code
COPY . .

# Expose the port the app runs on
EXPOSE 8000

# Define the command to run the application
ENTRYPOINT ["python"]
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "app:app"]